name: Auto Restart and Keep Codespace Active

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:

jobs:
  restart_codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          if ! command -v gh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh jq
          fi

      - name: Authenticate GitHub CLI
        run: echo "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" | gh auth login --with-token

      - name: Debugging
        run: |
          pwd
          ls -la
          echo $PATH

      - name: Check Codespace Status
        run: |
          CODESPACE_NAME="unhallowed-spooky-hobgoblin-q7pxxvgg4p67c9gjr"
          # (Add your code checking status and handling here)

      - name: Run Python Script
        run: |
          gh codespace ssh --codespace "$CODESPACE_NAME" --command "python3 sahil.py"
