name: Auto Restart and Keep Codespace Active

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  restart_codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI if not present
        run: |
          if ! command -v gh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh jq
          fi

      - name: Authenticate GitHub CLI with Personal Access Token
        run: |
          echo "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" | gh auth login --with-token

      - name: Check Codespace Status and Keep Alive
        run: |
          CODESPACE_NAME="unhallowed-spooky-vampire-r4594xp5vw53rr5"
          STATUS=$(gh codespace list --json name,state -q ".[] | select(.name == \"$CODESPACE_NAME\") | .state")
          
          if [ -z "$STATUS" ]; then
            echo "Error fetching codespace status or codespace does not exist."
            exit 1
          fi

          echo "Codespace status: $STATUS"

          if [ "$STATUS" == "Shutdown" ]; then
            echo "Codespace is offline. Attempting to start it..."
            gh codespace ssh --codespace "$CODESPACE_NAME" --command "echo Codespace started!"
          else
            echo "Codespace is active. Sending keep-alive signal..."
            gh codespace ssh --codespace "$CODESPACE_NAME" --command "echo Keep-alive signal"
          fi
